name: Go Test and Tag

on: [ push, workflow_dispatch ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Run tests
        run: go test -v ./...
        
      - name: Update commit status
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const status = process.exitCode === 0 ? 'success' : 'failure';
            const github = context.github;
            await github.repos.createCommitStatus({
              ...context.repo,
              sha: context.sha,
              state: status,
              target_url: 'https://example.com', // Optional URL for more details
              description: `Go tests ${status}`,
              context: 'go-tests'
            });
